---
engines:
  fixme:
    enabled: true
    config:
      strings:
        - FIXME
        - TODO
        - HACK
        - MAYBELATER
        - MAYBE-LATER
ratings:
  paths: []
# exclude_paths:
# - tests/
